### ISSUE TITLE
Plugin not working in my jenkins

### ISSUE THREAD

**Issue by agk2** [jenkinsci/service-now-plugin#15]
Hi,
I have install this plugin in my Jenkins instance and tested it with pipeline it giving me below error.
java.net.UnknownHostException: https: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
Below is my configurstion.
    def response = serviceNow_createChange serviceNowConfiguration: [instance: 'https://****/api/gjd/change_api/postRecord',producerId: 'ls98y3khifs8oih3kjshihksjd'],credentialsId: '****',serviceNowItem: [body: messageJson]
If I remove http then it give response with status 400

**Comment by pdkreid** [comment]
@agk2 The instance that you are passing into the plugin is incorrect. You need to only pass in the host value for you service-now instance. For example, if you service-now instance is at mycompany.service-now.com, your instance value would just be 'mycompany'

**Comment by agk2** [comment]
thanks, @pdkreid for your response, when I pass the only instance value getting status 401, though credential have access to service now API which I tested through rest service

**Comment by agk2** [comment]
Due to some policy at our enterprise, it was not working. After taking approval of it worked, closing this issue.
